# Generated by Django 4.1.3 on 2022-11-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.CharField(max_length=255),
        ),
    ]
